
				SECTION vector
				include "asmdef.h"
				GLOBAL FconfigInterruptVector
				ORG	P:
FconfigInterruptVector:
				jsr     FarchStart
				jsr     FarchStart
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FInterrupt18
				jsr     FInterrupt19
				jsr     FInterrupt20
				jsr     FInterrupt21
				jsr     FInterrupt22
				jsr     FInterrupt23
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FfcodecStereoISR
				jsr     FfcodecStereoISR
				jsr     FInterrupt59
				jsr     FInterrupt60
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FconfigUnhandledInterruptISR
				jsr     FarchStart
				jsr     FarchStart
				movei   #-482,X0


				ORG	X:

				ENDSEC
				END
