/*****************************************************************************
*
* Motorola Inc.
* (c) Copyright 2000 Motorola, Inc.
* ALL RIGHTS RESERVED.
*
******************************************************************************
*
* File Name: demo711.c
*
* Description: Demos G711.
*
* Modules Included:
*                   main () -  C function
*
* Author: Sandeep S
*
* Date: 03 Aug 2000
*
*****************************************************************************/

#include "g711.h"
#include "test.h"

/* Codec related header files */
#include "bsp.h"
#include "fcntl.h"
#include "codec.h"

#define  NUMSPEECH_SAMPLES  32

/*****************************************************************************
*
* Module: main()
*
* Description: This is a realtime demo for PCM Encoding and
*              Decoding. The Analog speech/audio is fed to 
*              Line-in input of the EVM. The Codec is configured
*              for 8-Khz sampling rate (see appconfig.h).
*
*              This demo converts the linear samples to A-law
*              and then back to linear and then sends the output
*              samples to Codec output. The Line-Out port on the 
*              EVM should be connected to a speaker or a headphone.
*
* Returns: None
*
* Arguments: None
*
* Range Issues: None
*
* Special Issues: None
*
* Test Method: Tested through demo_g711.mcp
*
***************************** Change History ********************************
* 
*    DD/MM/YYYY     Code Ver     Description      Author
*    ----------     --------     -----------      ------
*    03-08-2000     0.1          Created          Sandeep Sehgal
*    05-08-2000     1.0          Baselined        Sandeep Sehgal
*
*****************************************************************************/

void main()
{
    test_sRec testRec;
    
    /* Codec TX & RX buffers and variables */
    Word16   CodecTxBuffer[32];  /* Samples generated by the transmitter */
    Word16   CodecRxBuffer[32];  /* Samples for the receiver */
    Word16   Codec;
    UWord16  num_words;
    /* Codec structure */
	codec_sParams CodecParams;
    
    /* Codec initialization */
	Codec = open(BSP_DEVICE_NAME_CODEC_0, O_RDWR);

	CodecParams.Buffer.Size      = 64;
	CodecParams.Buffer.Threshold = 0;

	ioctl(Codec, CODEC_DEVICE_RESET, (void *) &CodecParams);
	
    testStart(&testRec, "Demo of A-law Encoding");
    testComment(&testRec, "Please Speak using Microphone");    	
	
    while (1)
    {
    
        num_words = 0;

        do {
           
           /* Read Linear Samples from Codec Input*/
			num_words += read(Codec, (CodecRxBuffer + num_words),
			             NUMSPEECH_SAMPLES - num_words);

		   } while (num_words < NUMSPEECH_SAMPLES);
		   
        /* Linear to A-law and back to Linear Conversion*/		   
        g711_linear2alaw(CodecRxBuffer, CodecTxBuffer, 32);
        g711_alaw2linear(CodecTxBuffer, CodecTxBuffer, 32); 
         
        /* Wrtite to Codec output*/               
		write(Codec, CodecTxBuffer, NUMSPEECH_SAMPLES);                 

    }        	
    
}
